export const REAL_DISH_EXAMPLES: string[] = [
  "Alföldi sertéskaraj tarhonyával",
  "Alföldi tejfölös pulykaragu tésztával",
  "Almás kacsamájjal töltött szelet vegyes körettel",
  "Almával töltött csirkemell rántva vegyes körettel",
  "Almával és sajttal töltött csirkemell rántva vegyes körettel",
  "Ananászos csirkemell főtt rizzsel",
  "Aszalt szilvával töltött pulykamell rántva vegyes körettel",
  "Baconba göngyölt csirkemell sajttal töltve vegyes körettel",
  "Baconba tekert csirkemell vegyes körettel",
  "Baconbe tekert csirkemell rántva vegyes körettel",
  "Baconbe tekert pulykamellfilé steak burgonyával",
  "Baconkrémmel töltött pulykamell burgonyával és káposztával",
  "Baconkrémmel töltött pulykamell rántva vegyes körettel",
  "Baconos sertéstokány spagettivel",
  "Baconos-hagymás rántott pulykamell kukoricás jázmin rizzsel",
  "Baconos-sonkás ragu spagettivel",
  "Bajor fasírt szezámos bundában vegyes körettel",
  "Bajor zöldséges fasírt burgonyasalátával",
  "Bakonyi gombás csirkecomb tésztával",
  "Bakonyi gombás ragu tésztával",
  "Bakonyi gombás sertéscomb grillezett kukoricalepénnyel",
  "Bakonyi sertéskaraj tésztával",
  "Barackos csirkemell burgonyafánkkal",
  "Barbecue csirkecomb párolt zöldséggel",
  "Barbecue csirkecombfilé forgatott burgonyával",
  "Barbecue csirkecombfilé hagymás-paprikás burgonyával",
  "Barbecue csirkecombfilé steak burgonyával",
  "Barbecue csirkecombfilé tzatzikivel",
  "Barbecue csirkemell chilis burgonyapürével",
  "Barbecue csirkemell grill zöldségekkel",
  "Barbecue csirkemell jázmin rizzsel és salátával",
  "Barbecue csirkemell majonézes zöldborsó salátával és rizzsel",
  "Barbecue csirkemell rizzsel és ceruzababbal",
  "Barbecue csirkeszárny steak burgonyával",
  "Barbecue pulykacomb forgatott burgonyával",
  "Barbecue pulykamell steak burgonyával",
  "Barbecue ropogós párolt zöldséggel és burgonyával",
  "Bazsalikomos fasírtgolyócskák joghurtos vitaminsalátával",
  "Bazsalikomos pulykaragu durum tésztával",
  "Berlini sertéskaraj párolt rizzsel",
  "Berlini töltött pulykamell rántva párolt baconos ceruzababbal",
  "Bolognai palacsinta rántva párolt zöldséges rizzsel",
  "Bolognai palacsinta vegyes körettel",
  "Bolognai spagetti",
  "Bolognai spagetti mozzarellával",
  "Bolognai spagetti reszelt sajttal",
  "Borsos tokány durum tésztával",
  "Borsos tokány rizzsel",
  "Borsos tokány steak burgonyával",
  "Borsos tokány tésztával",
  "Borsos tokány árpagyönggyel",
  "Boszorkány ragu tarhonyával",
  "Brassói aprópecsenye",
  "Brokkolis csirkemell főtt jázmin rizzsel",
  "Brokkolis csirkemell árpagyönggyel",
  "Brokkolis jércecomb vegyes körettel",
  "Brokkolis sertéskaraj tésztával",
  "Brokkolis-tejfölös csirkemell tésztával",
  "Brokkolis-tejszínes csirkemell tésztával",
  "Brokkolival töltött csirkemell rántva burgonyapürével",
  "Buffalo csirkeszárny zöldséges jázmin rizzsel",
  "Buffalo csirkeszárnyak chilis rizzsel",
  "Bundázott csirkecombfilé zelleres pürével",
  "Burgonyás tészta",
  "Bácskai rizses hús",
  "Bácskai rizses hús házi csalamádéval",
  "Cajuni fűszeres jércecombfilé ceruzababbal",
  "Camambert sajt rántva burgonyapürével és lekvárral",
  "Carbonara spagetti",
  "Champion gomba paprikás tarhonyával",
  "Chilis aprópecsenye",
  "Chilis aprópecsenye rizzsel",
  "Chilis bab",
  "Chilis-barbecue csirkeszárny burgonyával",
  "Cigánypecsenye serpenyős burgonyával",
  "Citromos pulykaragu túrós tésztával",
  "Citromos sertéskaraj jázmin rizzsel",
  "Cornflakes-ben sült csirkemell kókuszos rizzsel",
  "Csabai kolbászhússal töltött csirkemell rántva vegyes körettel",
  "Csabai töltött karaj burgonyalángossal",
  "Csibefasírt burgonyával és káposztasalátával",
  "Csibemájjal töltött csirkemell burgonyával és bébirépával",
  "Csibemájjal töltött csirkemell vegyes körettel",
  "Csibemájjal töltött pulykamell tejfölös burgonyapürével",
  "Csirkecomb rántva zabpelyhes bundában vegyes körettel",
  "Csirkecombcsíkocskák zöldséges rizzsel",
  "Csirkecombfilé Budapest-módra",
  "Csirkecombfilé bécsiesen burgonyasalátával",
  "Csirkecombfilé párolt zöldséggel és főtt burgonyával",
  "Csirkecombfilé roston vegyes körettel",
  "Csirkecombfilé rántva lila hagymás burgonyapürével",
  "Csirkecombfilé rántva sajtmártással és rizzsel",
  "Csirkecombfilé sajtos burgonyapürével",
  "Csirkecombfilé zöldséges bulgurral",
  "Csirkecombpaprikás túrós csuszával",
  "Csirkemell Hawaii-módra",
  "Csirkemell cheddar sajtmártással és spagettivel",
  "Csirkemell piccata paradicsomos-pesztós rizzsel",
  "Csirkemell pirított gombával és párolt rizzsel",
  "Csirkemellcsík rántva vegyes körettel",
  "Csirkemellcsíkok rántva petrezselymes burgonyával",
  "Csirkemellfilé toszkán-módra penne tésztával",
  "Csirkemellpaprikás durum tésztával",
  "Csirkemellpaprikás tésztával",
  "Csirkepaprikás tarhonyával és csemegeuborkával",
  "Csirkés Pad-Thai",
  "Csirkés-zöldséges paiella",
  "Csongrádi töltött pulykamell rántva vegyes körettel",
  "Csongrádi töltött pulykamell vegyes körettel",
  "Csáki szalmájával töltött jércemell rántva vegyes körettel",
  "Csípős csirkefilé árpagyönggyel",
  "Csípős csirkemell tésztával",
  "Csípős-savanyú csirkemell basmati rizzsel",
  "Csípős-savanyú csirkemell jázmin rizzsel",
  "Csípős-savanyú ragu rizzsel",
  "Csülök Pékné-módra lecsós burgonyával",
  "Csülökpörkölt burgonyával",
  "Csőben sült brokkolis csirke",
  "Csőben sült karfiol",
  "Csőben sült sajtos brokkoli",
  "Csőben sült sajtos zöldségek",
  "Csőben sült sajtos-tejszínes karfiol",
  "Csőben sült zöldségek trappista sajttal",
  "Cukkini sajtos bundában sült rizzsel",
  "Cukkinis csirkemell rizzsel",
  "Cukkinis csirkemell tésztával",
  "Cukkinis csirkés rizs",
  "Currys csirke züld salátával",
  "Currys csirkemell rizzsel",
  "Dijoni mustáros csirkecombfilé tepsis burgonyával",
  "Dijoni mustáros petrezselymes pulykaragu tésztával",
  "Dijoni mustáros sertéskaraj tésztával",
  "Dorozsmai rakott csirkecomb vegyes körettel",
  "Dubarry csirkemell burgonyapürével",
  "Dubarry csirkemell vegyes körettel",
  "Dubarry pulyka burgonyapürével",
  "Dubarry pulykamell burgonyapürével",
  "Egészben sült barbecue sertéskaraj burgonyapürével",
  "Egészben sült csirkemell mustáros mártásban tésztával",
  "Egészben sült karaj párolt káposztával és hagymás burgonyával",
  "Egészben sült karaj tejfölös-kapros mártással",
  "Egészben sült köményes sertéskaraj",
  "Egészben sült sertéscomb hagymás burgonyával és csemegeuborkával",
  "Egészben sült sertéskaraj hagymamártással és zöldséges rizzsel",
  "Egészben sült tarja párolt hagymával szalvéta gombóccal",
  "Elzászi húsos káposzta",
  "Erdei mézes jércecomb almaszósszal",
  "Eszterházy szelet makarónival",
  "Falusi göngyölt csirke vegyes körettel",
  "Falusi göngyölt csirkemell vegyes körettel",
  "Falusi sertéskaraj nokedlivel",
  "Fetás csirkecombfilé vegyes körettel",
  "Firenzei csirkemell spagettivel",
  "Firenzei spagetti",
  "Fokhagymás aprópecsenye",
  "Fokhagymás aprópecsenye rántva párolt bulguros rizzsel",
  "Fokhagymás aprópecsenye steak burgonyával",
  "Fokhagymás csibemáj forgatott burgonyával",
  "Frankfurti sertésragu tésztával",
  "Füstölt sajt rántva burgonyapürével, tartármártással",
  "Füstölt sajtkrémmel töltött pulykamell vegyes körettel",
  "Füstölt sajttal töltött csirkemell steak burgonyával",
  "Füstölt sajttal töltött pulykamell rántva tejszínes bébirépával",
  "Füstölt sajttal töltött pulykamell rántva vegyes körettel",
  "Füstölt sonkával töltött pulykamell vegyes körettel",
  "Fűszeres csibemáj főtt burgonyával",
  "Fűszeres húsgombóc paradicsomszósszal",
  "Genovai csirkemell csavart durum tésztával",
  "Genovai csirkemell durum tésztával és reszelt sajttal",
  "Genovai csirkemell makarónival",
  "Genovai pulykamell penne tésztával",
  "Genovai ragu makarónival",
  "Gombapaprikás tejfölös spagettivel",
  "Gombapaprikás tojásos nokedlivel",
  "Gombás sertéscomb párolt zöldséges rizzsel",
  "Gombás-paprikás pulykaragu tésztával",
  "Gombás-sonkás csirkecomb petrezselymes burgonyával",
  "Gombás-sonkás sertéscomb paprikás rizzsel",
  "Goudával töltött sertéskaraj rántva vegyes körettel",
  "Grillezett csirkecomb sült almával és petrezselymes rizzsel",
  "Grillezett csirkemell cheddar sajtmártással rizi-bizivel",
  "Grillezett csirkemell csíkok párolt zöldséggel",
  "Grillezett csirkemell csípős pennével",
  "Grillezett csirkemell mustáros-tejfölös öntettel",
  "Grillezett csirkemell párolt zöldséggel",
  "Grillezett csirkemell salátával és joghurtos öntettel",
  "Grillezett csirkemell tárkonyos török joghurttal,paprikás jázmin rizzsel",
  "Grillezett csirkemell wok zöldséggel ás árpagyönggyel",
  "Grillezett csirkemellszelet bazsalikomos paradicsomsalátával",
  "Grillezett pulykacsíkok vaslapos zöldséggel",
  "Gyros hús rizzsel tzatzikivel",
  "Gyros sáfrányos rizzsel",
  "Gyros tokány",
  "Gyros tokány bulgurral",
  "Gyros tokány jázmin rizzsel",
  "Gyros tokány sáfrányos rizzsel",
  "Gyros tokány török joghurtos öntettel",
  "Gyros tál rizzsel és salátával",
  "Gyulai sertéskaraj vegyes körettel",
  "Görög csirke bulgurral és tzatzikivel",
  "Görög fasírt salátával",
  "Görögsaláta fetasajttal és pirított csirkecombbal",
  "Hagymás-brokkolis sertéskaraj burgonyával",
  "Hagymás-sonkás szárnyasmáj tört burgonyával",
  "Hawaii csirkemell főtt rizzsel",
  "Hawaii csirkemell rizzsel és salátával",
  "Hawaii csirkemell sonkás rizzsel",
  "Hentes tokány pirított tarhonyával",
  "Hentes tokány párolt rizzsel",
  "Háromízű sertéskaraj steak burgonyával",
  "Indiai csirkemell basmati rizzsel",
  "Indiai csirkemell főtt rizzsel",
  "Indiai zöldséges csirkemell sült rizzsel",
  "Indiai édes-savanyú csirkecomb rizzsel",
  "Indonéz csirke főtt rizzsel",
  "Indonéz rizs hússal zöldséggel és jázmin rizzsel",
  "Indonéz rizs hússal és zöldséggel",
  "Indonéz rizses hús",
  "Juhtúróval töltött csirkemell forgatott burgonyával",
  "Juhtúróval töltött csirkemell hagymás-kínai keles bulgurral",
  "Juhtúróval töltött csirkemell rántva vegyes körettel",
  "Juhtúróval töltött pulykamell rántva vegyes körettel",
  "Juhtúróval töltött pulykamell vegyes körettel",
  "Jércefilé újhagymás párolt zöldséggel",
  "Jércemell steak burgonyanudlival",
  "Kacsamájjal töltött pulykamell petrezselymes burgonyával",
  "Kapros csirkemell rizi-bizivel",
  "Kapros sertéscomb tésztával",
  "Kapros túróval töltött csirkemell tört burgonyával",
  "Kapros túróval töltött rántott sajt burgonyapürével és tartármártással",
  "Kapros-tejszínes csirkecomb tésztával",
  "Kemencés csirkemell párolt borsóval és répával",
  "Kemencés csirkemell tejszínes bébirépával",
  "Kemencés csirkemell tormamártással, hagymás burgonyával",
  "Kemencés csirkemell zöldségfasírttal",
  "Kemencés jércecombfilé lecsós burgonyával",
  "Kemencés mézes csirkecomb tarhonyával és párolt zöldséggel",
  "Kemencés pulykamell tejszínes zöldkörettel",
  "Kemencés sertéscsülök burgonyával, paprika mártással",
  "Kemencés sertéskaraj parasztos burgonyával",
  "Kemencés zöldséges sertéskaraj durum tésztával",
  "Kentucky csirkeszárny steak burgonyával",
  "Kentucky csirkeszárnyak farmer burgonyával",
  "Kentucky csirkeszárnyak steak burgonyával",
  "Kentucky csirkeszárnyak zöldséges rizzsel",
  "Kijevi csirkemell burgonyával és tejszínes brokkolival",
  "Kijevi jércemell gratin burgonyával",
  "Kijevi pulykamell rántva párolt borsóval, bébirépával",
  "Kijevi pulykamell rántva vegyes körettel",
  "Kolbászos pulykaragu tarhonyával",
  "Korianderes csirkemell jázmin rizzsel",
  "Korianderes keleti csirkemell árpagyönggyel és rizzsel",
  "Köményes sertéskaraj hagymás burgonyával és párolt káposztával",
  "Körözöttel töltött csirkemell magvas bundában petrezselymes burgonyával",
  "Lasagna",
  "Lecsós csibemáj burgonyával",
  "Lecsós csibemáj hagymás burgonyával",
  "Lecsós csirkecombfilé főtt burgonyával",
  "Lecsós sertéskaraj",
  "Lecsós sertéskaraj rántva vegyes körettel",
  "Magos kabátban forgatott csirkemell párolt ceruzababbal",
  "Magyaros csibemáj burgonyával",
  "Magyaros csibemáj burgonyával és csemegeuborkával",
  "Magyaros csibemáj forgatott burgonyával",
  "Magyaros csibemáj főtt burgonyával",
  "Magyaros csibemáj vaslapos burgonyával",
  "Magyaros paprikás gulyás tarhonyával, csemegeuborkával",
  "Magyaros rizses hús csemegeuborkával",
  "Magyaros rizseshús csemegeuborka tzatzikivel",
  "Magyaróvári sertéskaraj tejszínes pennével",
  "Malacsült lecsós burgonyával és hagymamártással",
  "Marhapörkölt főtt burgonyával",
  "Medvehagymás fasírtgolyó tejfölös burgonyával",
  "Medvehagymás sajttal töltött pulykamell párolt káposztával",
  "Mentás zöldborsófőzelék csirkemellel",
  "Mexikói chilis bab",
  "Mexikói csirkemell bulgurral",
  "Mexikói csirkemell párolt rizzsel",
  "Mexikói csülkös bab",
  "Mexikói húsos chilis bab",
  "Mexikói sertéskaraj főtt rizzsel",
  "Milánói csirkemell spagettivel",
  "Milánói makaróni",
  "Milánói sertésborda",
  "Milánói spagetti",
  "Mozzarellával töltött csirkemell rántva tejszínes zöldkörettel",
  "Mozzarellával töltött pulykamell rántva vegyes körettel",
  "Mozzarellával-pesztóval töltött jércefilé zöldséges burgonyával",
  "Mustáros csirkemellcsíkok rántva bébirépával",
  "Mustáros pulykamell rántva hagymás burgonyával",
  "Mustáros sertéskaraj durum tésztával",
  "Mustáros sertéskaraj rántva steak burgonyával",
  "Máltai tonhalas tészta",
  "Mátrai borzaska (tócsniban sült csirkemell)",
  "Mézes sült csirkecomb káposztás csuszával",
  "Mézes-chilis csirkecombfilé steak burgonyával",
  "Mézes-mustáros csirkemell grill zöldséggel, bulgurral",
  "Mézes-mustáros csirkemell tojásos rizzsel",
  "Mézes-mustáros csirkemell tésztával",
  "Nagymama töltött pulykamelle rántva vegyes körettel",
  "Narancsos jércefilé steak burgonyával",
  "Natúr csirkemell almafőzelékkel",
  "Natúr csirkemell paradicsomos bulgurral és párolt brokkolival",
  "Natúr csirkemell salátával és zöldséges bulgurral",
  "Natúr csirkemell tejszínes cukkinivel és paradicsomos rizzsel",
  "Natúr pulykamellszelet tejszínes gombával és burgonyával",
  "PAD-THAI csirkemell jázmin rizzsel",
  "Palócragu tepsis burgonyával",
  "Paprikás burgonya kolbásszal és savanyúsággal",
  "Paprikás csirkemell káposztás árpagyönggyel",
  "Paprikás csirkemell tésztával",
  "Paprikás krumpli kolbásszal és virslivel",
  "Paprikás sertéscomb tarhonyával és káposztasalátával",
  "Paradicsomos fasírtgolyók főtt burgonyával",
  "Paradicsomos húsgombóc",
  "Paradicsomos penne",
  "Paradicsomos pulykaragu burgonyával",
  "Paraszt kolbászos paprikás burgonya nokedlivel",
  "Pekingi csirke sült tojásos rizzsel",
  "Pesztós csirkemell penne tésztával",
  "Pesztós darált szárnyasragu főtt durum tésztával",
  "Pesztós gombaragu makarónival",
  "Pesztós penne jércemellcsíkocskákkal",
  "Pesztós pulykamellcsíkocskák tésztával",
  "Pikáns sertéskaraj burgonya nudlival",
  "Pikáns-tejfölös sertéskaraj durum tésztával",
  "Pirított csibemáj főtt burgonyával",
  "Pirított gombás pulykamell jázmin rizzsel",
  "Pizzaiola burgonyával és salátával",
  "Pizzaiola cukkinis rizzsel",
  "Pizzaiola pulykamell párolt rizzsel",
  "Pizzaiola szelet steak burgonyával",
  "Pizzaiola szelet vegyes körettel",
  "Pizzaiola szelet vegyes párolt zöldségekkel",
  "Pleskavica ajvárral",
  "Pleskavica ajvárral pirított hagymás burgonyával",
  "Pleskavica forgatott burgonyával",
  "Pleskavica hagymás bulgurral",
  "Pontypaprikás tépett csuszával",
  "Provance-i sertéskaraj gombás rizzsel",
  "Prágai borda vegyes körettel",
  "Prágai sertéscomb steak burgonyával",
  "Pulykacombpörkölt kagylótésztával",
  "Pulykamell Orly-módra zöldséges rizzsel",
  "Pulykamell pirított gombával és párolt rizzsel",
  "Pulykamell pirított gombával, rizi-bizivel",
  "Pulykamell rántva burgonyával és párolt bébirépával",
  "Pulykamell rántva hagymás burgonyával",
  "Pulykamell steak rántva burgonyával",
  "Pulykamell tavaszi zöldségágyon mozzarellával pirítva",
  "Pulykamellfilé pirított gombával és főtt burgonyával",
  "Pulykapaprikás fűszeres nokedlivel",
  "Pusztapörkölt tarhonyával",
  "Pácolt csirkecomb brokkolival és főtt rizzsel",
  "Párizsi bundás pulykamell párolt zöldséggel",
  "Párizsi csirkemell bulgurral és párolt zöldséggel",
  "Párizsi csirkemell steak burgonyával",
  "Párizsi jércefilé petrezselymes burgonyával",
  "Párizsi sertéskaraj párolt répával és rizzsel",
  "Pármai spagetti",
  "Pásztor tarhonya",
  "Rakott brokkoli",
  "Rakott burgonya",
  "Rakott erdélyi káposzta",
  "Rakott húsos zöldséges rizs",
  "Rakott karfiol",
  "Rakott kel",
  "Rakott kelkáposzta",
  "Rakott mexikói húsos rizs",
  "Rakott sonkás tészta",
  "Rakott zöldbab",
  "Rakott zöldséges csirkecomb",
  "Rakott zöldséges csirkemell",
  "Rakott zöldséges pulykacomb",
  "Rakott zöldséges rizses hús",
  "Resztelt csibemáj hagymás burgonyával",
  "Ropogós csirkecomb rozmaringos burgonyával",
  "Ropogós csirkemellcsíkok burgonyapürével",
  "Ropogós sertéskaraj lecsós burgonyával",
  "Roston csirkecombfilé rizzsel és zöldborsóval",
  "Roston csirkemell sajtos cukkinivel és pesztós rizzsel",
  "Rozmaringos-tejfölös pulykaragu párolt rizzsel",
  "Rántott camambert áfonya lekvárral",
  "Rántott csirke mellfilé belső filé nélkül (külső filé)",
  "Rántott csirkecombfilé petrezselymes burgonyával",
  "Rántott csirkemell burgonyával és párolt bébirépával",
  "Rántott cukkini joghurtos salátával",
  "Rántott cukkini joghurtos öntettel",
  "Rántott cukkini párolt répával",
  "Rántott gomba salátával",
  "Rántott karfiol salátával",
  "Rántott sajt burgonyapürével és tartármártással",
  "Rántott sajt burgonyapürével és tiroli káposztasalátával",
  "Rántott sajt burgonyasalátával",
  "Rántott sajt joghurtos vitaminsalátával",
  "Rántott sajt sokmagvas bundában burgonyával és izlandi salátával",
  "Rántott sajt szezámos bundában tartármártással és burgonyapürével",
  "Rántott sajt tartár mártással és burgonyapürével",
  "Rántott sajt tartár mártással és tejfölös burgonyapürével",
  "Rántott sajt tartármártással",
  "Rántott sajt tartármártással és burgonyapürével",
  "Rántott sajt vegyes körettel",
  "Rántott sertésborda cheddar sajtmártással és bulgurral",
  "Rántott trappista sajt fokhagymás burgonyapürével és tartármártással",
  "Rántott trappista sajt majonézes burgonyával",
  "Rántott trappista sajt tartármártással",
  "Római köményes csirkecsík rántva vegyes körettel",
  "Sajtban forgatott kemencés csirkemell rizi-bizivel",
  "Sajtbundás csirkemell burgonyával és párolt kínai kellel",
  "Sajtbundás csirkemell vegyes körettel",
  "Sajtbundás csirkemell zöldséges bulgurral",
  "Sajtkrémmel töltött csirkemell rántva burgonyával és párolt répával",
  "Sajtkrémmel töltött sertéskaraj vegyes körettel",
  "Sajtos csibefasírt rolád paradicsomos burgonyával",
  "Sajtos csirkecombfilé kerti zöldekkel",
  "Sajtos zöldséges rakott rizses hús",
  "Sajtos-húsos ropogós párolt zöldséggel és rizzsel",
  "Sajtos-húsos ropogós vegyes körettel",
  "Sajtos-sonkás sertéskaraj paradicsomos bulgurral",
  "Sajtos-tejfölös párizsi csirkemell burgonyával",
  "Sajtos–húsos ropogós grill zöldségekkel",
  "Sajttal töltött baconba göngyölt csirkemell vegyes körettel",
  "Sajttal töltött csirkemell rántva petrezselymes burgonyával",
  "Sajttal töltött csirkemell rántva vegyes körettel",
  "Sajttal-baconnal töltött csirkemell vegyes körettel",
  "Sajttal-sonkával töltött csirkemell rántva vegyes körettel",
  "Sajttal-sonkával töltött csirkemell zöldséges rizzsel",
  "Sajttal-sonkával töltött pulykamell párolt répával",
  "Sajttal-sonkával töltött pulykamell rántva alma és répa pürével",
  "Sajttal-sonkával töltött pulykamell rántva kemencés burgonyával",
  "Sajttal-sonkával töltött pulykamell rántva milánói tésztával",
  "Sertésborda cheddar sajtos mártással",
  "Sertéscomb Pékné-módra",
  "Sertéscomb pirított hagymával és burgonyapürével",
  "Sertéscombpaprikás tarhonyával",
  "Sertéscombpörkölt nokedlivel",
  "Sertéscsülök pezsgős káposztával",
  "Sertéscsülök sütve burgonyasalátával",
  "Sertéskaraj Orly-módra hagymás burgonyával és párolt répával",
  "Sertéskaraj berlini-módra vegyes körettel",
  "Sertéskaraj rántva burgonyapürével",
  "Sertéskaraj vadasmártással és durum tésztával",
  "Sertéspaprikás tésztával és csemegeuborkával",
  "Sertéspörkölt pirított tarhonyával",
  "Sertéspörkölt tarhonyával",
  "Sertéssült pirított burgonyával és párolt elzászi káposztával",
  "Snidlinges-sajtos krémmel töltött pulykamell vegyes körettel",
  "Snidlingkrémmel töltött pulykamell rántva vegyes körettel",
  "Sokmagvas bundában rántott pulykamell vegyes körettel",
  "Sokmagvas csirkecombcsíkocskák burgonyapürével",
  "Sokmagvas csirkecombfilé rántva káposztasalátával",
  "Sokmagvas csirkecsíkok rántva burgonyával",
  "Sokmagvas csirkemell rántva burgonyával és lila káposztával",
  "Sokmagvas csirkemellcsík rántva hagymás burgonyával",
  "Sokmagvas csirkemellcsíkok rántva burgonyapürével",
  "Sokmagvas pulykacombcsíkok rántva vegyes körettel",
  "Sokmagvas pulykamell párolt rizzsel és szőlőmártással",
  "Sokmagvas ropogós sertéskaraj vegyes körettel",
  "Sokmagvas rántott csirkecomb párolt répával",
  "Sokmagvas rántott sajt burgonyával és bébirépával",
  "Sokmagvas rántott sajt szegedi burgonyasalátával",
  "Sokmagvas rántott sajt tartárral és petrezselymes burgonyával",
  "Sonkakrémmel töltött csirkemell rántva vegyes körettel",
  "Sonkakrémmel töltött csirkemell vegyes körettel",
  "Sonkakrémmel töltött pulykamell rántva gratin burgonyával",
  "Sonkás rakott tészta",
  "Sonkás rántott sajttekercs burgonyával és tartármártással",
  "Sonkás-sajtos paradicsomos penne",
  "Sonkával töltött csirkemell rántva burgonyával és vegyes zöldséggel",
  "Sonkával töltött csirkemell rántva chilis rizzsel",
  "Sonkával töltött csirkemell rántva párolt zöldséggel",
  "Sonkával töltött pulykamell rizzsel",
  "Sonkával töltött pulykamell vegyes körettel",
  "Sonkával töltött sajt rántva vegyes körettel",
  "Stefánia vagdalt francia salátával",
  "Stefánia vagdalt tepsis burgonyával",
  "Stefánia vagdalt uborkasalátával",
  "Svájci zöldséges röszti barbecue csirkével",
  "Szalonnába göngyölt pulykamell forgatott burgonyával",
  "Szalonnás csibemáj burgonyapürével",
  "Szecsuáni csirke jázmin rizzsel",
  "Szecsuáni jérceragu jázmin rizzsel",
  "Szegedi rizses hús",
  "Szerb gyuvecs",
  "Szezámmagos csirkecsíkok rántva vegyes körettel",
  "Szezámos csirkecsík rántva mézes-chilis rizzsel",
  "Szezámos csirkemell rántva forgatott burgonyával",
  "Szezámos csirkemell vegyes körettel",
  "Szezámos rántott pulykamell uborkasalátával",
  "Szárnyashúsos rakott zöldséges rizs",
  "Székelygulyás gerslivel",
  "Székelykáposzta",
  "Székelykáposzta tejföllel",
  "Székelykáposzta tejföllel és árpagyönggyel",
  "Székelykáposzta árpagyönggyel",
  "Szójaszószos-pfefferonis csirkemell jázmin rizzsel",
  "Sörtésztában sült pulykamell tepsis burgonyával",
  "Sörtésztás sertéskaraj burgonyapürével",
  "Sült csirkecomb párolt almás káposztával",
  "Sült csirkecomb párolt káposztával",
  "Sült csirkecomb párolt káposztával és új burgonyával",
  "Sült csirkecomb párolt káposztával, steak burgonyával",
  "Sült csirkecomb steak burgonyával és párolt káposztával",
  "Sült csirkecomb vegyes körettel",
  "Sült csirkecombfilé burgonyával és párolt káposztával",
  "Sült csirkecombfilé párolt káposztával és hagymás burgonyával",
  "Sült csirkés zöldséges tészta",
  "Sült sertésoldalas burgonyával és csemegeuborkával",
  "Sült sertéstarja párolt káposztával és burgonyával",
  "TOM-YAM csirke jázmin rizzsel",
  "TOM-YAM csirkemell jázmin rizzsel",
  "Tandori csirkemell tésztával",
  "Tavaszi zöldséges csirkemell bulgurral",
  "Tejfölös-borsós csirkemell főtt rizzsel",
  "Tejfölös-gombás karfiol (vega)",
  "Tejfölös-kapros sertésborda forgatott burgonyával",
  "Tejszínes-baconos csirkés penne",
  "Tejszínes-gombás pulykacomb jázmin rizzsel",
  "Tejszínes-gombás pulykamell durum tésztával",
  "Tejszínes-gombás-húsos tészta",
  "Tejszínes-kapros csirkemell rizzsel",
  "Tejszínes-mustáros csirkemell kagylótésztával",
  "Tejszínes-zöldborsós sertéskaraj jázmin rizzsel",
  "Tejszínes-zöldséges pulykamell tésztával",
  "Tejszínes-zöldséges sertéskaraj",
  "Temesvári sertésborda pirított tarhonyával",
  "Temesvári sertésborda tésztával",
  "Temesvári sertésborda árpagyönggyel",
  "Temesvári sertéscomb metélt tésztával",
  "Temesvári sertéskaraj rizzsel",
  "Thai citromfüves csirke sült zöldséges tésztával",
  "Thai csirkemellcsíkok szezámos bundában párolt zöldkörettel",
  "Thai kókusztejes csirkemell rizstésztával",
  "Thai zöldséges ragu rizzsel",
  "Tiszai aprópecsenye",
  "Tiszai aprópecsenye basmati rizzsel",
  "Tom-Yam csirke üvegtésztával",
  "Tonhalas-paradicsomos makaróni",
  "Trappista sajt rántva burgonyapürével és tartármártással",
  "Trappista sajt rántva burgonyával és salátával",
  "Trappista sajt rántva majonézes burgonyasalátával",
  "Trappista sajt rántva petrezselymes burgonyával és salátával",
  "Tzatzikis csirke spanyol burgonyával",
  "Tárkonyos csirkecomb főtt rizzsel",
  "Tárkonyos csirkemell főtt durum tésztával",
  "Tárkonyos pulykacombragu durum tésztával",
  "Tárkonyos pulykaragu durum tésztával",
  "Tárkonyos pulykaragu tésztával",
  "Töltött csirkecombfilé forgatott burgonyával",
  "Töltött paprika főtt burgonyával",
  "Török joghurtos csirkecomb bulgurral",
  "Túrós csusza szalonnapörccel",
  "Tüzes csirkemell basmati rizzsel",
  "Tüzes csirkemell főtt rizzsel",
  "Tüzes csirkemellragu borsós rizzsel",
  "Tüzes jércecombfilé rizzsel",
  "Tüzes pfefferonis csirkemell jázmin rizzsel",
  "Vaslapos csibemáj hagymás burgonyával",
  "Vaslapos csirkecomb almafőzelékkel",
  "Vaslapos csirkecomb grill zöldséggel",
  "Vaslapos csirkecomb káposzta salátával",
  "Vaslapos csirkecomb párolt zöldséggel",
  "Vaslapos csirkecombfilé kreol raguval",
  "Vaslapos csirkecombfilé tejszínes zöldkörettel",
  "Vaslapos csirkemell cukkinivel és petrezselymes burgonyával",
  "Vaslapos csirkemell grill zöldséggel",
  "Vaslapos csirkemell párolt zöldséggel és burgonyapürével",
  "Vaslapos csirkemell rizzsel és párolt zöldborsóval",
  "Vaslapos csirkemell tejszínes brokkolival és baconos burgonyával",
  "Vaslapos csirkemellcsíkok grill zöldséggel",
  "Vaslapos hagymás-kukoricás csirkeragu",
  "Vaslapos jércecomb forgatott burgonyával",
  "Vaslapos jércecomb párolt répával és zöldborsóval",
  "Vaslapos jércecsíkok főtt rizzsel, ezersziget mártással",
  "Vaslapos sertéskaraj paprikás burgonyával",
  "Vegyes zöldséges pulykacomb tésztával",
  "Velővel töltött csirkemell rántva burgonya rösztivel",
  "Velővel töltött palacsinta petrezselymes burgonyával",
  "Velővel töltött pulykamell rántva hagymás burgonyával",
  "Velővel töltött pulykamell rántva vegyes körettel",
  "Veronai csirke burgonyával és cukkinivel",
  "Veronai csirkemell pennével",
  "Veronai fussilli",
  "Veronai jércecomb tésztával",
  "Vietnami sült rizs csirkével",
  "Vietnami zöldséges csirkemell tojásos rizzsel",
  "Vörösboros csirkecomb tésztával",
  "Vörösboros pulykapörkölt burgonyával",
  "Wingz csirkemell rántva párolt zöldséggel",
  "Wingz csirkeszárnyak",
  "Wok zöldséges csirkecomb párolt rizzsel",
  "Wok zöldséges csirkemell jázmin rizzsel",
  "Wok zöldséges jércemell jázmin rizzsel",
  "Wok zöldséges jércemell rizzsel",
  "Wok zöldséges pulykamell rizzsel",
  "Zeusz fetás sertéskaraj tejfölös sopszka salátával",
  "Zsályás csirkecombragu káposztás tésztával",
  "Zsályás-citromos pulykaragu tésztával",
  "Zsályás-fokhagymás pulykaragu tésztával",
  "Zöldborsófőzelék csibefasírttal",
  "Zöldborsófőzelék fasírttal",
  "Zöldborsós csirkemell rizzsel",
  "Zöldfűszeres sajtkrémmel töltött csirkemell rántva vegyes körettel",
  "Zöldségbundás csirkemell forgatott burgonyával",
  "Zöldségbundás csirkemell főtt rizzsel és ceruzababbal",
  "Zöldségbundás csirkemell vegyes körettel",
  "Zöldségbundás pulykamell tejszínes párolt zöldséggel",
  "Zöldséges csibefasírt steak burgonyával",
  "Zöldséges rizses hús",
  "Zöldséges ropogós rizzsel és fokhagymás majonézzel",
  "Zöldséges sertéskaraj makarónival",
  "Zöldséges sertéskaraj tésztával",
  "Zöldségfasírt burgonyasalátával",
  "Zúzapörkölt nokedlivel",
  "Ázsiai csirke rizzsel",
  "Édes-savanyú csirke gőzölt rizzsel",
  "Édes-savanyú csirkemell jázmin rizzsel",
  "Újhagymás csirkemellragu bulgurral",
  "Újhagymás-sajtos csirkemell paradicsomos bulgurral",
  "Újhagymás-sajtos jércemell paradicsomos pennével"
];
